### ISSUE TITLE
- [ ] Definir el título del proyecto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo3_jag_ppi2020#1]

**Comment by camilahernandez16** [comment]
Misión Gramatical

**Comment by camilahernandez16** [comment]
Nuestro proyecto tiene por nombre, Misión Gramatical

**Comment by JohnFlorez25** [comment]
@camilahernandez16 El título debe estar en la wiki, cumple con lo acordado según el proyecto que van a realizar
