### ISSUE TITLE
- [ ] Diseñar el diagrama de espina de pescado

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo3_jag_ppi2020#2]

**Comment by GeraldineTequia** [comment]
![Espina de pescado](https://user-images.githubusercontent.com/66040433/85868750-51934100-b790-11ea-9f52-8940be1e523e.jpeg)

**Comment by JohnFlorez25** [comment]
@GeraldineTequia El diagrama cumple con el análisis e identificación del problema
