### ISSUE TITLE
- [ ] Declarar la situación del problema

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo3_jag_ppi2020#3]

**Comment by GeraldineTequia** [comment]
**Situación del problema** 
Los estudiantes del grado tercero presentan dificultades al realizar sus actividades en el área de lengua castellana, ya que se les dificulta a la hora de escribir el no saber diferenciar las palabras o no tener muy buena ortografía. Esto ocurre debido a que los estudiantes generalmente presentan desinterés por la clase, no tienen el acompañamiento familiar adecuado en la realización de los trabajos y tareas y en ocasiones los docentes no utilizan metodologías adecuadas para la edad y la capacidad de aprendizaje de algunos estudiantes y como causa de estas dificultades se vio la necesidad de crear un aplicativo, el cual permita a los estudiantes de una forma más didáctica  mejorar y reforzar temas ya vistos en el área de lengua castellana.

**Comment by JohnFlorez25** [comment]
@GeraldineTequia Hay que redefinir los aspectos a nivel del efecto del problema identificado, en la descripción de la situación del problema no podemos decir la solución, en este caso el aplicativo móvil
