### ISSUE TITLE
- [ ] Describir cada uno de los interesados

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo3_jag_ppi2020#4]

**Comment by GeraldineTequia** [comment]
[Descripción de los interesados.docx](https://github.com/JohnFlorez25/equipo3_jag_ppi2020/files/4837576/Descripcion.de.los.interesados.docx)

**Comment by JohnFlorez25** [comment]
@GeraldineTequia @Laura-gon @Alissvas21 @camilahernandez16 Cómo mínimo deben existir tres interesados cumpliendo  con:

- Quienes van a usar el sistema
- Quienes estén interesados en que el sistema este en marcha o que se realice.
- Entidades
