### ISSUE TITLE
- [ ] Construir Tablero de Visión del Producto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo3_jag_ppi2020#5]

**Comment by GeraldineTequia** [comment]
[Visión del producto.docx](https://github.com/JohnFlorez25/equipo3_jag_ppi2020/files/4837632/Vision.del.producto.docx)

**Comment by JohnFlorez25** [comment]
@GeraldineTequia ampliar la descripción de la visión del producto y como mínimo por cada categoría diferente a los interesados identificar 4 elementos.
